### PR TITLE
Please check and tell me needed changes

### PR DESCRIPTION
**Pull request by nilupulmanodya**
### Description

1. Replacing Null values
2. Remove unwanted features and rows
3. Change categorical data types to categorical

### Checklist

- [x]  I am making a proper pull request, not spam.

- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

Preprocess the dataset : Handling NULL values & Duplicate features #1

### CODE REVIEW

**Review by niloysikdar — COMMENTED** [review]
@sagnik1511 please review this pr and merge if everything seems good.

**Comment by sagnik1511** [comment]
```
df = df.astype('category')
df.dtypes
```

Hey @nilupulmanodya , can you explain what have you done here?

**Comment by sagnik1511** [comment]
As the issue only asks the contributor to handle the null values and the duplicates feature/rows, the updates in the PR should be strictly on those only.

**Comment by nilupulmanodya** [comment]
hey @sagnik1511 ,
I thought that's easy for data clustering. I can reverse it. How about you feel other things ? can you satisfy or need any changes ?

**Comment by sagnik1511** [comment]
As the numeric feature can hold a euclidian distance feature, thus needed in numeric values.

**Comment by nilupulmanodya** [comment]
Sure, I will change it

**Comment by sagnik1511** [comment]
Looks like you're new to GitHub. No need to close the PR. If you update the branch, it will directly reflect in the PR.

**Comment by nilupulmanodya** [comment]
Thank you so much. I will try in next time.

**Pull request closed without merging**
